### ISSUE TITLE
Do I need pull-up resistors?

### ISSUE THREAD

**Issue by Matheus-de-Souza** [peej/for-science-keyboard#6]
I build the keyboard, but it doesn't works with the two halfs together. Do I need to put the pull-up resistor as the documentation said here https://docs.qmk.fm/#/feature_split_keyboard?id=i2c-wiring?

**Comment by peej** [comment]
No, it should be using a serial connection rather than i2c. It may be that QMK has changed in the last 5 years and the firmware config needs an update if you are building from the latest QMK, but first check that the 3 serial pins are connected correctly so there is continuity through your TRRS cable.

**Comment by Matheus-de-Souza** [comment]
ah, ok. Thank you! But I liked to use each half with its own configuration, it seems to me easier to manage all the layers. Thank you a lot for sharing your project it's amazing!
